### ISSUE TITLE
Strict types?

### ISSUE THREAD

**Issue by mlocati** [concrete5/console#13]
I'm a big fan of strongly typed languages.

What about adding `declare(strict_types=1);` to the files, and adding parameter/return types whenever possible?

**Comment by KorvinSzanto** [comment]
Absolutely worth doing, we can add `RequireStrictTypesSniff` to phpcs as well to enforce it.

**Comment by KorvinSzanto** [comment]
>.. and adding parameter/return types whenever possible
This should already be required by psalm, anywhere the type is ambiguous it should require that you specify but I might not be remembering the settings correctly.
