### ISSUE TITLE
concrete command: symfony error

### ISSUE THREAD

**Issue by crydotsnake** [concrete5/console#5]
Hello,

i installed the concrete5-console package via composer, and `export PATH=~/.composer/vendor/bin:$PATH` is in my `.zshrc` file.

But `concrete info` returns:

```
Fatal error: Cannot redeclare dd() (previously declared in /Users/expl0it/.composer/vendor/symfony/var-dumper/Resources/functions/dump.php:35) in /Users/expl0it/.composer/vendor/concrete5/console/helpers.php on line 7
```

How can i fix that?.

**Comment by KorvinSzanto** [comment]
We need to namespace our helper functions to prevent collisions like this. It's a small library, there's no reason we can't just use them every time we need them.

**Comment by crydotsnake** [comment]
Good too know ^^

**Comment by KorvinSzanto** [comment]
#8 will avoid this issue

**Comment by KorvinSzanto** [comment]
Use the phar release of `>=0.1.0` to avoid this issue completely. Thanks @mlocati!
