### ISSUE TITLE
Publishing the project as a phar?

### ISSUE THREAD

**Issue by mlocati** [concrete5/console#8]
What about this approach?

We create a GitHub Action that listen to tags creation.

When a new version-like (`/^(v\.?)?\d+.\d+.\d.*$/`) tag is pushed, the action would create a phar containing the whole project, create a [release](https://github.com/concrete5/console/releases), and attach the phar to it.

Assuming that we "rename" the entrypoint as ccm (see https://github.com/concrete5/console/issues/6), that way we'd be able to fetch the whole project as a single executable file, with something like:

```sh
curl -L -o /usr/local/bin/ccm https://github.com/concrete5/console/releases/latest/download/ccm.phar
chmod +x /usr/local/bin/ccm
```

I do really prefer this approach: installing it via `composer global require` is slower, and global composer.json may contain requirements that are incompatible with this project.

**Comment by KorvinSzanto** [comment]
I agree, I'm fully on board with building a phar, I'm just not quite ready to swap the name yet.

**Comment by mlocati** [comment]
Done in #14
